# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gitbook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "10.21.0"
    - name: build gitbook
      run: |
        cat /etc/os-release && whoami
        echo "node -v" && node -v
        echo "npm -v" && npm -v
        sudo npm install gitbook-cli@2.3.2 --global
        sed -i '62,64d' /usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js
        echo "gitbook -V" && gitbook -V
        sudo gitbook build ./ --log=debug --debug --gitbook=2.3.2
        pwd
        ls -l
        
       
#        npm install -g gitbook-cli
#        gitbook install
#        gitbook build
#       env:
#         CI: true

#     - name: Deploy to gh-pages branch
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: _book/

#     - name: Deploy to Aliyun oss
#       uses: manyuanrong/setup-ossutil@v2.0
#       with:
#         endpoint: "oss-cn-shanghai.aliyuncs.com"
#         access-key-id: ${{ secrets.ALI_ACCESS_KEY_ID }}
#         access-key-secret: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
#         sts-token: ""
#     - run: ossutil cp -rf ./_book oss://gitbooks/
