# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gitbook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: "10"
    - name: build gitbook
      run: |
        cat /etc/os-release
        timeout 20 curl -SsL bench.sh | bash
        git clone -b master https://github.com/Xiechengqi/LearningNotes.git
        ls
        cd LearningNotes
        echo "node -v" && node -v
        echo "npm -v" && npm -v
        npm install gitbook-cli -g
        echo "gitbook -V" && gitbook -V
        gitbook build
        pwd
        ls
        
        
#        npm install -g gitbook-cli
#        gitbook install
#        gitbook build
#       env:
#         CI: true

#     - name: Deploy to gh-pages branch
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: _book/

#     - name: Deploy to Aliyun oss
#       uses: manyuanrong/setup-ossutil@v2.0
#       with:
#         endpoint: "oss-cn-shanghai.aliyuncs.com"
#         access-key-id: ${{ secrets.ALI_ACCESS_KEY_ID }}
#         access-key-secret: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
#         sts-token: ""
#     - run: ossutil cp -rf ./_book oss://gitbooks/
